In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('Data.csv')

In [3]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
data.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [5]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [9]:
x = data.iloc[:,0:3].values
y = data.iloc[:,-1].values

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [12]:
from sklearn.impute import SimpleImputer

In [16]:
impute = SimpleImputer(missing_values=np.nan,strategy='mean')
impute.fit(x[:,1:3])
x[:,1:3] = impute.transform(x[:,1:3])

In [17]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [23]:
ct = ColumnTransformer(transformers=[('encode',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [24]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
lb = LabelEncoder()
y = lb.fit_transform(y)

In [27]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [33]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [34]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [35]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [36]:
y_test

array([0, 1])

In [37]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc = StandardScaler()
x_train[:,0:3] = sc.fit_transform(x_train[:,0:3])
x_test[:,0:3] = sc.transform(x_test[:,0:3])

In [41]:
x_train

array([[-0.7745966692414835, -0.5773502691896258, 1.2909944487358058,
        38.77777777777778, 52000.0],
       [-0.7745966692414835, 1.7320508075688774, -0.7745966692414835,
        40.0, 63777.77777777778],
       [1.2909944487358058, -0.5773502691896258, -0.7745966692414835,
        44.0, 72000.0],
       [-0.7745966692414835, -0.5773502691896258, 1.2909944487358058,
        38.0, 61000.0],
       [-0.7745966692414835, -0.5773502691896258, 1.2909944487358058,
        27.0, 48000.0],
       [1.2909944487358058, -0.5773502691896258, -0.7745966692414835,
        48.0, 79000.0],
       [-0.7745966692414835, 1.7320508075688774, -0.7745966692414835,
        50.0, 83000.0],
       [1.2909944487358058, -0.5773502691896258, -0.7745966692414835,
        35.0, 58000.0]], dtype=object)

In [42]:
x_test

array([[2.775557561562892e-17, 1.0, 0.0, 30.0, 54000.0],
       [1.0000000000000002, 4.163336342344337e-17, 0.0, 37.0, 67000.0]],
      dtype=object)